import style from './carForm.module.scss';
import {onChangeDefault} from "@/components/utils/formUtils";
import {useState} from "react";
import InputButton from "@/app/requests/new/inputButton/inputButton";
import {useRouter} from "next/navigation";
import PostDrivers from "@/app/API/postDrivers";
import PostCar from "@/app/API/postCar";
import BlockInput from "@/app/requests/new/blockInput/blockInput";
import getCoordsByAddress from "@/app/API/geocoder";
import {XMLParser} from "fast-xml-parser";

export default function CarForm(props) {
    const close = (e) => {
        e.preventDefault()
        props.setOpenForm(!props.openForm)
    }

    const [values, setValues] = useState({
        "timetable": [
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F"
        ]
    });

    const parser = new XMLParser();
    const rever = async (start) => {
        let result = {
            ...start
        }
        let loc = await getCoordsByAddress(start.location, parser)
        result["latitude"] = loc.lats;
        result["longitude"] = loc.long;

        return result
    }

    let link = useRouter()
    async function submitHandler (e) {
        e.preventDefault();

        await PostCar.sendRequest(await rever(values));

        props.setOpenForm(!props.openForm)
        setTimeout(() => {
            props.fun()
            link.push('/fleet');
        }, 100)
    }

    const selectArray = [
        {
            text: "Грузовой",
            value: "cargo"
        },
        {
            text: "Пассажирский",
            value: "human"
        },
        {
            text: "Грузо-пассажирский",
            value: "all"
        },
    ];

    return (
        <div className={style.main}>
            <div className={style.block}>

                <button className={style.close} onClick={close} style={{zIndex: '99'}}>+</button>

                <p>Регистрация автомобиля</p>

                <div>
                    <BlockInput gridName={"A"} type={'text'} text={"Номер автомобиля"} placeholder={"а123аа"} require={true} name={"numberOfTransport"} onChange={(e) => onChangeDefault(e, values, setValues)}/>
                    <BlockInput gridName={"A"} type={'text'} text={"Название автомобиля"} placeholder={"Лада Гранта"} require={true} name={"name"} onChange={(e) => onChangeDefault(e, values, setValues)}/>
                    <BlockInput gridName={"A"} type={'select'} text={"Тип автомобиля"} placeholder={"Не выбран"} require={true} name={"title"} selectArray={selectArray} onChange={(e) => onChangeDefault(e, values, setValues)}/>
                    <BlockInput gridName={"A"} type={'integer'} text={"Максимальное количество посадочных мест"} placeholder={""} require={true} name={"maxNumberOfPassengersInCar"} onChange={(e) => onChangeDefault(e, values, setValues)}/>
                    <BlockInput gridName={"A"} type={'integer'} text={"Максимальная грузоподъёмность"} placeholder={"кг"} require={true} name={"maxAmountOfCargoInCar"} onChange={(e) => onChangeDefault(e, values, setValues)}/>
                    <BlockInput gridName={"A"} type={'text'} text={"Адрес автопарка"} placeholder={""} require={true} name={"location"} onChange={(e) => onChangeDefault(e, values, setValues)}/>
                </div>

                <div className={style.button} onClick={submitHandler}>Создать автомобиль</div>
            </div>
        </div>
    )
}