import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "@/components/static/header/header";
import Menu from "@/components/static/menu/menu";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SGK',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Menu />
        {children}
      </body>
    </html>
  )
}
